name: flowdock-notification

on:
  pull_request:
    branches:
      - master

jobs:
  flowdock-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Flowdock when a pull request is made
    steps:
      - name: Send message to Flowdock API
        uses: ./
        with:
          flowdock-bot-access-token: ${{ secrets.TEAM_FLOW_ACCESS_TOKEN }}
          text: "@team, ${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url }}"
